---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/token/access":
    post:
      summary: create token
      tags:
      - Authentication
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                api_key:
                  type: string
              required:
              - api_key
  "/api/v1/token/refresh":
    post:
      summary: refresh token
      tags:
      - Authentication
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                refresh_token:
                  type: string
              required:
              - refresh_token
  "/api/v1/url/shorten":
    post:
      summary: create url
      tags:
      - URL Shortener
      security:
      - bearerAuth: []
      parameters: []
      responses:
        '201':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                target_url:
                  type: string
              required:
              - target_url
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: 127.0.0.1:3000/
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
